version: "3"

services:
  xiaoquan-api:
    image: xiaoquan-docker-registry.cn-beijing.cr.aliyuncs.com/xiaoquan/api-stage:latest
    container_name: xiaoquan-api-stage
    volumes:
      - ./logs/api:/www/storage/logs
      - ./.env:/www/.env
    ports:
      - "8081:80"
      - "8088:81"
    cap_add:
      - SYS_PTRACE
    restart: always
