version: "3"

services:
  xiaoquan-api:
    image: docker-hub.chqaz.com/xiaoquan/api-test:latest
    container_name: xiaoquan-api-test
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./logs/api:/www/storage/logs
      - ./.env:/www/.env
    ports:
      - "8082:80"
      - "8089:81"
    cap_add:
      - SYS_PTRACE
    restart: always
