version: "3"

services:
  xiaoquan-api:
    image: docker-hub.chqaz.com/xiaoquan/api:latest
    container_name: xiaoquan-api-prod
    volumes:
      - ./logs/api:/www/storage/logs
      - ./.env:/www/.env
    ports:
      - "8081:80"
      - "8088:81"
    cap_add:
      - SYS_PTRACE
    restart: always
